import CloudQueueIcon from '@mui/icons-material/CloudQueue';
import WorkspacesIcon from '@mui/icons-material/Workspaces';
import WindowIcon from '@mui/icons-material/Window';
import BadgeIcon from '@mui/icons-material/Badge';
import LockIcon from '@mui/icons-material/Lock';
import DevicesOtherIcon from '@mui/icons-material/DevicesOther';
import GppMaybeIcon from '@mui/icons-material/GppMaybe';
import PhishingIcon from '@mui/icons-material/Phishing';
import BugReportIcon from '@mui/icons-material/BugReport';
import ShieldIcon from '@mui/icons-material/Shield';
import ArticleIcon from '@mui/icons-material/Article';
import VisibilityIcon from '@mui/icons-material/Visibility';
import CloudDoneIcon from '@mui/icons-material/CloudDone';
// `logoUrl` can be either:
// - a local path served from /public, e.g. '/logos/aws.svg' (recommended — see note below)
// - a full remote URL, e.g. 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/aws.svg'
// - '' / undefined, in which case ProviderCard falls back to the MUI `Icon`
//
// Recommended: download the real SVG once (from dashboardicons.com or the
// vendor's own brand/press page) and drop it in public/logos/<key>.svg, then
// just set logoUrl: '/logos/<key>.svg' below. That avoids depending on a
// third-party CDN staying online/unchanged for a product your clients rely on.
export const BUILT_IN_PROVIDERS = [
  {
    key: 'aws',
    label: 'Amazon Web Services',
    shortLabel: 'AWS',
    accent: '#FF9900',
    Icon: CloudQueueIcon,
    logoUrl: '/logos/aws.svg',
    description: 'IAM, S3, CloudTrail, GuardDuty',
  },
  {
    key: 'gws',
    label: 'Google Workspace',
    shortLabel: 'Google WS',
    accent: '#4285F4',
    Icon: WorkspacesIcon,
    logoUrl: '/logos/google-workspace.svg',
    description: 'Admin SDK, Drive, Audit Logs',
  },
  {
    key: 'm365',
    label: 'Microsoft 365',
    shortLabel: 'M365',
    accent: '#0078D4',
    Icon: WindowIcon,
    logoUrl: '/logos/microsoft-365.svg',
    description: 'Azure AD, SharePoint, Defender',
  },
  {
    key: 'keka',
    label: 'Keka HR',
    shortLabel: 'Keka',
    accent: '#E84C3D',
    Icon: BadgeIcon,
    logoUrl: '/logos/keka.svg',
    description: 'Core HR, Leave, Attendance',
  },
  {
    key: 'vault',
    label: 'HashiCorp Vault',
    shortLabel: 'Vault',
    accent: '#000000',
    Icon: LockIcon,
    logoUrl: '/logos/hashicorp-vault.svg',
    description: 'Secrets, dynamic credentials, PKI',
  },
  {
    key: 'jumpcloud',
    configKey: 'jumpCloud',
    label: 'JumpCloud',
    shortLabel: 'JumpCloud',
    accent: '#14283D',
    Icon: DevicesOtherIcon,
    logoUrl: '/logos/jumpcloud.svg',
    description: 'Device & identity management',
  },
  {
    key: 'otx',
    label: 'OTX AlienVault',
    shortLabel: 'OTX',
    accent: '#00A8E0',
    Icon: GppMaybeIcon,
    logoUrl: '/logos/otx-alienvault.svg',
    description: 'Threat intelligence feed',
  },
  {
    key: 'gophish',
    label: 'GoPhish',
    shortLabel: 'GoPhish',
    accent: '#5D4E8C',
    Icon: PhishingIcon,
    logoUrl: '/logos/gophish.svg',
    description: 'Phishing simulation & training',
  },
  {
    key: 'snyk',
    label: 'Snyk',
    shortLabel: 'Snyk',
    accent: '#4C4A73',
    Icon: BugReportIcon,
    logoUrl: '/logos/snyk.svg',
    description: 'Code & dependency scanning',
  },
  {
    key: 'cloudflare',
    label: 'Cloudflare',
    shortLabel: 'Cloudflare',
    accent: '#F38020',
    Icon: ShieldIcon,
    logoUrl: '/logos/cloudflare.svg',
    description: 'WAF, firewall, TLS enforcement',
  },
  {
    key: 'notion',
    label: 'Notion',
    shortLabel: 'Notion',
    accent: '#000000',
    Icon: ArticleIcon,
    logoUrl: '/logos/notion.svg',
    description: 'Policy & documentation tracking',
  },
  {
    key: 'wazuh',
    label: 'Wazuh',
    shortLabel: 'Wazuh',
    accent: '#3253DC',
    Icon: VisibilityIcon,
    logoUrl: '/logos/wazuh.svg',
    description: 'Vulnerability & log monitoring',
  },
  {
    key: 'confluence',
    label: 'Confluence',
    description: 'Policy & documentation tracking',
    Icon: ShieldIcon, // or whatever fallback icon import you use elsewhere
    logoUrl: '/logos/confluence.svg',
    accent: '#172B4D',
  },
  {
    key: 'pfsense',
    label: 'pfSense',
    description: 'Firewall rules & network segmentation',
    Icon: VisibilityIcon, // fallback icon
    logoUrl: '/logos/pfsense.svg',
    accent: '#212121',
  },
  {
    key: 'crowdstrike',
    label: 'CrowdStrike Falcon',
    accent: '#E01F27',
    description: 'Endpoint protection, vulnerability exposure, and threat detections.',
    Icon: ShieldIcon,
    logoUrl: '/logos/crowdstrike.svg',
  },
  {
    key: 'owaspzap',
    label: 'OWASP ZAP',
    accent: '#4B0082',
    description: 'Dynamic application security testing (DAST) findings by risk.',
    Icon: BugReportIcon,
    logoUrl: '/logos/owaspzap.svg', // optional — falls back to Icon if missing
    configKey: 'owaspZap',
  },
  {
    key: 'keycloak',
    label: 'Keycloak',
    description: 'Open-source identity & access management',
    Icon: ShieldIcon, // or whatever fallback icon import you use elsewhere — SecurityIcon, LockIcon, etc.
    logoUrl: '/logos/keycloak.svg',
    accent: '#4D4D4D',
  },
  {
    key: 'paloalto',
    configKey: 'paloAlto',
    label: 'Palo Alto Networks',
    shortLabel: 'Palo Alto',
    description: 'Next-gen firewall & threat prevention',
    Icon: ShieldIcon,
    logoUrl: '/logos/paloalto.svg',
    accent: '#FA582D',
  },
  {
    key: 'graylog',
    label: 'Graylog',
    accent: '#FF3633',
    description: 'Centralized log management and SIEM',
    Icon: BugReportIcon, // import from '@mui/icons-material/ManageSearch'
    logoUrl: '/logos/graylog.svg', // optional, falls back to Icon if missing
  },
  {
    key: 'bitwarden',
    label: 'Bitwarden Teams',
    accent: '#175DDC',
    description: 'Team password vault and secrets management',
    Icon: ShieldIcon, // import from '@mui/icons-material/VpnKey'
    logoUrl: '/logos/bitwarden.svg',
  },
  {
    key: 'jamfpro',
    label: 'Jamf Pro',
    accent: '#26A055',
    description: 'MDM — Mobile & Endpoint Device Management',
    Icon: DevicesOtherIcon,
    logoUrl: '/logos/jamf.svg',
  },
  {
    key: 'misp',
    label: 'MISP Threat Intelligence',
    accent: '#A020F0',
    description: 'Threat intelligence events and security feeds sharing platform',
    Icon: BugReportIcon,
    logoUrl: '/logos/misp.svg',
  },
  {
    key: 'frigate',
    label: 'Frigate NVR',
    description: 'AI-powered local network video recording',
    Icon: VisibilityIcon,
    logoUrl: '/logos/frigate.svg',
    accent: '#06B6D4',
  },
  {
    key: 'verkada',
    label: 'Verkada',
    shortLabel: 'Verkada',
    accent: '#000000',
    Icon: VisibilityIcon,
    logoUrl: '/logos/verkada.svg',
    description: 'Cloud-based physical security, video security, and access control.',
  },
  {
    key: 'auth0',
    label: 'Auth0',
    shortLabel: 'Auth0',
    accent: '#EB5424',
    description: 'Authentication & authorization as a service',
    Icon: ShieldIcon,
    logoUrl: '/logos/auth0.svg',
  },
  {
    key: 'onelogin',
    label: 'OneLogin',
    shortLabel: 'OneLogin',
    accent: '#0D72B9',
    description: 'Identity & Access Management',
    Icon: ShieldIcon,
    logoUrl: '/logos/onelogin.svg',
  },
  {
    key: 'fortigate',
    label: 'FortiGate',
    shortLabel: 'FortiGate',
    accent: '#EE3124',
    description: 'Next-Generation Firewall & Security',
    Icon: ShieldIcon,
    logoUrl: '/logos/fortigate.svg',
  },
  // {
  //   key: 'intune',
  //   label: 'Microsoft Intune',
  //   shortLabel: 'Intune',
  //   accent: '#0078D4',
  //   description: 'Endpoint & Mobile Device Management',
  //   Icon: DevicesOtherIcon,
  //   logoUrl: 'https://logo.clearbit.com/microsoft.com',
  // },
  {
    key: 'proofpoint',
    label: 'Proofpoint',
    shortLabel: 'Proofpoint',
    accent: '#007ABF',
    description: 'Email Security & Protection',
    Icon: ShieldIcon,
    logoUrl: '/logos/proofpoint.svg',
  },
  {
    key: 'slack',
    label: 'Slack',
    shortLabel: 'Slack',
    accent: '#4A154B',
    description: 'Team Communication & Alerts',
    Icon: ArticleIcon,
    logoUrl: '/logos/slack.svg',
  },
  {
    key: 'sonarqube',
    label: 'SonarQube',
    shortLabel: 'SonarQube',
    accent: '#4E9BCD',
    description: 'Code Quality & Security Analysis',
    Icon: BugReportIcon,
    logoUrl: '/logos/sonarqube.svg',
  },
  {
    key: 'splunk',
    label: 'Splunk',
    shortLabel: 'Splunk',
    accent: '#000000',
    description: 'Data Analytics & SIEM',
    Icon: VisibilityIcon,
    logoUrl: '/logos/splunk.svg',
  },
  {
    key: 'onepassword',
    configKey: 'onepassword',
    label: '1Password',
    shortLabel: '1Password',
    accent: '#0572EC',
    description: 'Secrets vault, sign-in & audit events',
    Icon: ShieldIcon, // Using ShieldIcon as fallback because VpnKeyIcon is commented out at the top
    logoUrl: '/logos/1password.svg',
  },
  {
    key: 'servicenow',
    label: 'ServiceNow',
    shortLabel: 'ServiceNow',
    accent: '#81B5A1',
    description: 'ITSM, incident & policy tracking',
    Icon: ArticleIcon,
    logoUrl: '/logos/servicenow.svg',
  },
  {
    key: 'jsm',
    label: 'Jira Service Management',
    shortLabel: 'Jira SM',
    accent: '#2684FF',
    description: 'Helpdesk, incidents & change management',
    Icon: ArticleIcon,
    logoUrl: '/logos/jira.svg',
  },
  {
    key: 'hexnode',
    label: 'Hexnode',
    shortLabel: 'Hexnode',
    accent: '#2A2A2A',
    description: 'MDM — Mobile & Endpoint Device Management',
    Icon: DevicesOtherIcon,
    logoUrl: '/logos/hexnode.svg',
  },
  {
    key: 'gitlab',
    label: 'GitLab',
    shortLabel: 'GitLab',
    accent: '#FC6D26',
    description: 'Source code management & CI/CD pipeline security',
    Icon: ShieldIcon,
    logoUrl: '/logos/gitlab.svg',
  },
  {
    key: 'okta',
    label: 'Okta',
    shortLabel: 'Okta',
    accent: '#007DC1',
    description: 'Identity & Access Management',
    Icon: ShieldIcon,
    logoUrl: '/logos/okta.svg',
  },
  {
    key: 'datadog',
    label: 'Datadog',
    shortLabel: 'Datadog',
    accent: '#632CA6',
    description: 'Cloud monitoring & Security',
    Icon: ShieldIcon,
    logoUrl: '/logos/datadog.svg',
  },
  {
    key: 'sentinelone',
    label: 'SentinelOne',
    shortLabel: 'SentinelOne',
    accent: '#4A154B',
    Icon: ShieldIcon,
    logoUrl: '/logos/sentinelone.svg',
    description: 'Vulnerability management — endpoint agent coverage and critical vulnerability tracking.',
  },
  {
    key: 'duo',
    label: 'Duo Security',
    shortLabel: 'Duo',
    accent: '#6BC5F8',
    Icon: LockIcon,
    logoUrl: '/logos/duo.svg',
    description: 'Identity & Access Management (IAM) — user provisioning and MFA enforcement.',
  },
  {
    key: 'lastpass',
    label: 'LastPass',
    shortLabel: 'LastPass',
    accent: '#D32D27',
    Icon: LockIcon,
    logoUrl: '/logos/lastpass.svg',
    description: 'Password & Secret Management — vault authentication and shared-folder secret organization.',
  },
  {
    key: 'rapid7',
    label: 'Rapid7 InsightVM',
    shortLabel: 'Rapid7',
    accent: '#C8102E',
    Icon: BugReportIcon,
    logoUrl: '/logos/rapid7.svg',
    description: 'Vulnerability Management — scan site coverage and asset inventory tracking.',
  },
  {
    key: 'veracode',
    label: 'Veracode',
    shortLabel: 'Veracode',
    accent: '#EF4023',
    Icon: BugReportIcon,
    logoUrl: '/logos/veracode.svg',
    description: 'Code & Infrastructure Security (DevSecOps) — SAST/DAST application scan coverage.',
  },
  {
    key: 'zscaler',
    label: 'Zscaler',
    shortLabel: 'Zscaler',
    accent: '#00A4E4',
    Icon: ShieldIcon,
    logoUrl: '/logos/zscaler.svg',
    description: 'Network & Endpoint Security — zero trust web security policy enforcement.',
  },
  {
    key: 'netskope',
    label: 'Netskope',
    shortLabel: 'Netskope',
    accent: '#6ABE45',
    Icon: GppMaybeIcon,
    logoUrl: '/logos/netskope.svg',
    description: 'Data Loss Prevention & Classification — DLP profile coverage across cloud apps.',
  },
  {
    key: 'digitalguardian',
    label: 'Digital Guardian',
    shortLabel: 'Digital Guardian',
    accent: '#002554',
    Icon: LockIcon,
    logoUrl: '/logos/digital-guardian.svg',
    description: 'Data Loss Prevention & Classification — sensitive data policy coverage.',
  },
  // {
  // key: 'teams',
  // label: 'Microsoft Teams',
  // accent: '#6264A7',
  // description: 'Compliance sync alerts via Teams channel',
  // Icon: ForumIcon, // import from '@mui/icons-material/Forum'
  // logoUrl: '/logos/teams.svg',
  // },

  {
    key: 'elastic',
    label: 'Elastic Security',
    shortLabel: 'Elastic',
    accent: '#005571',
    Icon: VisibilityIcon,
    logoUrl: '/logos/elastic.svg',
    description: 'SIEM — detection rules & alerting pipeline health',
  },
  {
    key: 'qualys',
    label: 'Qualys VMDR',
    shortLabel: 'Qualys',
    accent: '#CC0000',
    Icon: BugReportIcon,
    logoUrl: '/logos/qualys.svg',
    description: 'Vulnerability Management — scanned host inventory and critical detection coverage.',
  },
  {
    key: 'sumologic',
    label: 'Sumo Logic',
    shortLabel: 'Sumo Logic',
    accent: '#004DFF',
    Icon: VisibilityIcon,
    logoUrl: '/logos/sumologic.svg',
    description: 'SIEM & Log Management — collector coverage and alerting pipeline health.',
  },
  {
    key: 'checkmarx',
    label: 'Checkmarx One',
    shortLabel: 'Checkmarx',
    accent: '#5A2D82',
    Icon: BugReportIcon,
    logoUrl: '/logos/checkmarx.svg',
    description: 'Code & Infrastructure Security (DevSecOps) — SAST scan coverage and secure coding posture.',
  },
  {
    key: 'cyberark',
    label: 'CyberArk',
    shortLabel: 'CyberArk',
    accent: '#000000',
    Icon: LockIcon,
    logoUrl: '/logos/cyberark.svg',
    description: 'Password & Secret Management — Safes provisioned and privileged accounts onboarded.',
  },
  {
    key: 'delinea',
    label: 'Delinea',
    shortLabel: 'Delinea',
    accent: '#005D90',
    Icon: LockIcon,
    logoUrl: '/logos/delinea.svg',
    description: 'Password & Secret Management — Secrets vaulted and auto password rotation enforced.',
  },
  {
    key: 'sailpoint',
    label: 'SailPoint',
    shortLabel: 'SailPoint',
    accent: '#0047BB',
    Icon: ShieldIcon,
    logoUrl: '/logos/sailpoint.svg',
    description: 'Identity & Access Management (IAM) — Identities provisioned and access certification campaigns.',
  },
  {
    key: 'pingidentity',
    label: 'Ping Identity',
    shortLabel: 'Ping Identity',
    accent: '#E82438',
    Icon: ShieldIcon,
    logoUrl: '/logos/pingidentity.svg',
    description: 'Identity & Access Management (IAM) — Users provisioned and MFA policy enabled.',
  },
  {
    key: 'meraki',
    label: 'Cisco Meraki',
    shortLabel: 'Meraki',
    accent: '#78BE20',
    Icon: ShieldIcon,
    logoUrl: '/logos/meraki.svg',
    description: 'Network Security & Firewall — cloud-managed firewall rules and network device health.',
  },
  {
    key: 'sentinel',
    label: 'Microsoft Sentinel',
    shortLabel: 'Sentinel',
    accent: '#0078D4',
    Icon: VisibilityIcon,
    logoUrl: '/logos/microsoft-sentinel.svg',
    description: 'SIEM & Log Management — analytics rule coverage and incident triage pipeline.',
  },
  {
    key: 'qradar',
    label: 'IBM QRadar',
    shortLabel: 'QRadar',
    accent: '#054ADA',
    Icon: VisibilityIcon,
    logoUrl: '/logos/qradar.svg',
    description: 'SIEM & Log Management — log source health and offense (alert) triage coverage.',
  },
  {
    key: 'logrhythm',
    label: 'LogRhythm',
    shortLabel: 'LogRhythm',
    accent: '#F47920',
    Icon: VisibilityIcon,
    logoUrl: '/logos/logrhythm.svg',
    description: 'SIEM & Log Management — log source health and open alarm triage coverage.',
  },

  // ── New: Wiz (Cloud Security Posture Management) ──────────────────────
  {
    key: 'wiz',
    label: 'Wiz',
    shortLabel: 'Wiz',
    accent: '#6E36E5',
    Icon: CloudDoneIcon,
    logoUrl: '/logos/wiz.svg',
    description: 'Cloud Security Posture Management (CSPM) — open critical cloud issues and connected cloud account coverage.',
  },

  // ── New: Sophos (Endpoint Protection) ──────────────────────────────────
  {
    key: 'sophos',
    label: 'Sophos Central',
    shortLabel: 'Sophos',
    accent: '#00B050',
    Icon: ShieldIcon,
    logoUrl: '/logos/sophos.svg',
    description: 'Endpoint Protection — endpoint agent coverage and unresolved threat/bad-health monitoring.',
  },

  // ── New: Recorded Future (Threat Intelligence) ──────────────────────────
  {
    key: 'recordedfuture',
    label: 'Recorded Future',
    shortLabel: 'Recorded Future',
    accent: '#C90C3E',
    Icon: GppMaybeIcon,
    logoUrl: '/logos/recorded-future.svg',
    description: 'Threat Intelligence — feed connectivity and high-risk indicator (IOC) monitoring.',
  },
  {
    key: 'tenable',
    label: 'Tenable',
    shortLabel: 'Tenable',
    accent: '#005571',
    Icon: ShieldIcon,
    logoUrl: '/logos/tenable.svg',
    description: 'Vulnerability management',
  },
  {
    key: 'pagerduty',
    label: 'PagerDuty',
    shortLabel: 'PagerDuty',
    accent: '#06D6A0',
    Icon: ArticleIcon,
    logoUrl: '/logos/pagerduty.svg',
    description: 'Incident response and alerting',
  },
  {
    key: 'mimecast',
    label: 'Mimecast',
    shortLabel: 'Mimecast',
    accent: '#111111',
    Icon: ShieldIcon,
    logoUrl: '/logos/mimecast.svg',
    description: 'Email security and compliance',
  },
  {
    key: 'freshservice',
    label: 'Freshservice',
    shortLabel: 'Freshservice',
    accent: '#12344D',
    Icon: ArticleIcon,
    logoUrl: '/logos/freshservice.svg',
    description: 'IT service management',
  },
  {
    key: 'orca',
    configKey: 'orcaSecurity',
    label: 'Orca Security',
    shortLabel: 'Orca',
    accent: '#000000',
    Icon: ShieldIcon,
    logoUrl: '/logos/orca.svg',
    description: 'Cloud security posture management',
  },
  {
    key: 'contrast',
    configKey: 'contrastSecurity',
    label: 'Contrast Security',
    shortLabel: 'Contrast',
    accent: '#EE3124',
    Icon: ShieldIcon,
    logoUrl: '/logos/contrast.svg',
    description: 'Application security testing',
  },
  {
    key: 'aqua',
    configKey: 'aquaSecurity',
    label: 'Aqua Security',
    shortLabel: 'Aqua',
    accent: '#007FFF',
    Icon: ShieldIcon,
    logoUrl: '/logos/aqua.svg',
    description: 'Cloud native security',
  },
  {
    key: 'exabeam',
    label: 'Exabeam',
    shortLabel: 'Exabeam',
    accent: '#000000',
    Icon: ShieldIcon,
    logoUrl: '/logos/exabeam.svg',
    description: 'SIEM and behavioral analytics',
  },
  {
    key: 'jfrogxray',
    label: 'JFrog Xray',
    shortLabel: 'JFrog Xray',
    accent: '#41BF4B',
    Icon: BugReportIcon,
    logoUrl: '/logos/jfrog.svg',
    description: 'Software composition analysis and security',
  },
  {
    key: 'semgrep',
    label: 'Semgrep',
    shortLabel: 'Semgrep',
    accent: '#000000',
    Icon: BugReportIcon,
    logoUrl: '/logos/semgrep.svg',
    description: 'Static application security testing',
  },
  {
    key: 'bitbucket',
    label: 'Bitbucket',
    shortLabel: 'Bitbucket',
    accent: '#2684FF',
    Icon: ArticleIcon,
    logoUrl: '/logos/bitbucket.svg',
    description: 'Source code management and CI/CD',
  },
  {
    key: 'github',
    label: 'GitHub',
    shortLabel: 'GitHub',
    accent: '#181717',
    Icon: ArticleIcon,
    logoUrl: '/logos/github.svg',
    description: 'Source code management and CI/CD',
  }
];
export const TYPE_COLORS = {
  CLOUD: 'primary', HRMS: 'secondary', IAM: 'warning',
  TICKETING: 'info', COMMUNICATION: 'success', CUSTOM: 'default',
};
